spring:
  profiles:
    active: dev
---
server:
  port: 8001
spring:
  profiles: dev
  application:
    name: microservicecloud-config-dept-client
  datasource:
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://58.87.108.138:3306/cloudDB01
      username: root
      password: Shijz192168@
      dbcp2:
        min-idle: 5                                #数据库连接池的最小维持连接数
        initial-size: 5                            #初始化连接数
        max-total: 5                               #最大连接数
        max-wait-millis: 200                       #等待连接获取的最大超时时间
mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml
  type-aliases-package: com.atguigu.springcloud.entities
  mapper-locations:
  - classpath:mybatis/mapper/**/*.xml

eureka:
  client:     #客户端注册进eureka服务列表内
    service-url:
      #defaultZone: http://localhost:7001/eureka    单机
      #集群配置
      defaultZone: http://eureka7001.com:7001/eureka/
  instance:
    instance-id: dept-8001.com  #用来自定义服务注册到eureka后的显示名称
    prefer-ip-address: true                 #访问路径可以显示IP地址

info: #用来显示服务入住到eureka注册中心的描述
  app.name: atguigu-microservicecloud-springcloudconfig01
  company.name: www.atguigu.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$


---
server:
  port: 8001
spring:
  profiles: test
  application:
    name: microservicecloud-config-dept-client
  datasource:
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://58.87.108.138:3306/cloudDB02
      username: root
      password: Shijz192168@
      dbcp2:
        min-idle: 5                                #数据库连接池的最小维持连接数
        initial-size: 5                            #初始化连接数
        max-total: 5                               #最大连接数
        max-wait-millis: 200                       #等待连接获取的最大超时时间
mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml
  type-aliases-package: com.atguigu.springcloud.entities
  mapper-locations:
  - classpath:mybatis/mapper/**/*.xml

eureka:
  client:     #客户端注册进eureka服务列表内
    service-url:
      #defaultZone: http://localhost:7001/eureka    单机
      #集群配置
      defaultZone: http://eureka7001.com:7001/eureka/
  instance:
    instance-id: dept-8001.com  #用来自定义服务注册到eureka后的显示名称
    prefer-ip-address: true                 #访问路径可以显示IP地址

info: #用来显示服务入住到eureka注册中心的描述
  app.name: atguigu-microservicecloud-springcloudconfig02
  company.name: www.atguigu.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$